//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTBan
    {
        public string IDChitietBan { get; set; }
        public string IDBan { get; set; }
        public string IDMatHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> DonGiaXuat { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual HoaDonBan HoaDonBan { get; set; }
        public virtual MatHang MatHang { get; set; }
    }
}
