//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatHang()
        {
            this.CTBans = new HashSet<CTBan>();
            this.CTNhaps = new HashSet<CTNhap>();
        }
    
        public string IDMatHang { get; set; }
        public string IDMuc { get; set; }
        public string Tenmathang { get; set; }
        public double DonGia { get; set; }
        public string BaoHanh { get; set; }
        public byte[] Anh { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string ChiTiet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTBan> CTBans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTNhap> CTNhaps { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
    }
}
