//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhLuong
    {
        public string IDTinhLuong { get; set; }
        public string IDNhanvien { get; set; }
        public string IDChucVu { get; set; }
        public Nullable<double> LuongCoBan { get; set; }
        public Nullable<double> Thuong { get; set; }
        public Nullable<double> Phat { get; set; }
        public Nullable<double> TongLuong { get; set; }
    
        public virtual HeSoChucVu HeSoChucVu { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
